apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: coderlang-enterprise
  labels:
    cloud.googleapis.com/location: us-central1
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/minScale: "0"
        autoscaling.knative.dev/maxScale: "5"
    spec:
      containers:
        - image: gcr.io/${PROJECT_ID}/coderlang-enterprise:latest
          ports:
            - containerPort: 8501
          resources:
            limits:
              cpu: "2000m"
              memory: "2Gi"
          env:
            - name: GOOGLE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: gemini-api-key
                  key: latest